### ISSUE TITLE
Project Quick-Start - Missing info on README 

### ISSUE THREAD

**Issue by app-generator** [admin-dashboards/nextjs-argon-dashboard#2]
Hello @Mortrest 

Please update the related section on README: how the users can use the product. 

Also, mention a recommended NodeJS version. 

https://github.com/admin-dashboards/nextjs-argon-dashboard#-quick-start

**Comment by Mortrest** [comment]
Added.

**Comment by admin-dashboards** [comment]
Closing. Ty @Mortrest
